<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFrameworks>net10.0;netstandard2.0</TargetFrameworks>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningsAsErrors />
    <ApplicationIcon />
    <StartupObject />
    <PackageVersion></PackageVersion>
    <Title>HotPotato.OpenApi</Title>
    <Authors>Hyland Test Automation Team</Authors>
    <Copyright />
    <Company />
    <Description>HotPotato.OpenApi contains all of the OpenAPI functionality including the processor implementation that validates an HTTP request/response pair against a spec, a result collection, logic to find paths, and so on. Currently, we are using the packages NSwag, NJsonSchema, and NJsonSchema.Yaml to consume a spec and to validate the contained schemas.</Description>
    <RepositoryUrl>https://github.com/davidmbillie/Hot-Potato</RepositoryUrl>
    <Configurations>Debug;Release;Docker</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NETCore.DotNetHostPolicy" Version="8.0.23" />
    <PackageReference Include="Namotion.Reflection" Version="3.4.3" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="NJsonSchema" Version="11.5.2" />
    <PackageReference Include="NJsonSchema.Yaml" Version="11.5.2" />
    <PackageReference Include="NSwag.Core" Version="14.6.3" />
    <PackageReference Include="NSwag.Core.Yaml" Version="14.6.3" />
    <PackageReference Include="YamlDotNet" Version="16.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HotPotato.Core\HotPotato.Core.csproj" />
  </ItemGroup>

</Project>
