---
name: hot-potato-ci

on:
  push:
    branches:
      - '!main'
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/build.yml

  # create-release:
  #   runs-on: ubuntu-latest
  #   if: ${{ success() }}
  #   steps:
  #     - name: Create Release
  #       run: gh release create ${{ job.build.steps.gitversion.outputs.nuGetVersionV2 }}
        # uses: actions/create-release@v1.1.4
        # if: ${{ success() }}
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        # with:
        #   tag_name: ${{ steps.gitversion.outputs.nuGetVersionV2 }}
        #   release_name: ${{ steps.gitversion.outputs.nuGetVersionV2 }}
        #   draft: false
        #   prerelease: false
