---
name: Hot Potato CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/build.yml

  create-tag:
    runs-on: ubuntu-latest
    steps:

      # - name: Checkout
      #   uses: actions/checkout@v4
      - name: Create tag
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${job.build.outputs.version}'
              sha: context.sha
            });

  push-package:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3.0.2
        with:
          name: nuget-packages
          path: ./nuget


      - name: NuGet push
        run: |
          dotnet nuget push ./nuget/**/*.nupkg \
            -k ${{ secrets.GITHUB_TOKEN }} \
            -s "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
            --skip-duplicate
  # create-release:
  #   runs-on: ubuntu-latest
  #   if: ${{ success() }}
  #   steps:
  #     - name: Create Release
  #       run: gh release create ${{ job.build.steps.gitversion.outputs.nuGetVersionV2 }}
        # uses: actions/create-release@v1.1.4
        # if: ${{ success() }}
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        # with:
        #   tag_name: ${{ steps.gitversion.outputs.nuGetVersionV2 }}
        #   release_name: ${{ steps.gitversion.outputs.nuGetVersionV2 }}
        #   draft: false
        #   prerelease: false
