---
###
# Runs a set of tests on the nuget packages to ensure functionality
###
name: Package Tests

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      version:
        description: "Version tag of the package to test."
        required: true
        type: string

jobs:
  # TODO: Need to get a Windows system to create a netframework example solution.
  # test-netframework:
  #   runs-on: windows-latest
  #   steps:
  #     - uses: actions/checkout@v4.0.0

  #     - name: Setup MSBuild
  #       uses: microsoft/setup-msbuild@v1.3.1

  #     - name: Setup NuGet
  #       uses: NuGet/setup-nuget@v1.2.0

  #     - name: Restore
  #       run: nuget restore ./examples/netframework/Example.sln

  #     - name: Build
  #       run: msbuild.exe ./examples/netframework/Example.sln /p:platform="Any CPU" /p:configuration="Release"

  test-net6:
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET 6.0
        uses: actions/setup-dotnet@v3.2.0
        with:
          dotnet-version: 6.0.x

      - name: Create and build test project
        run: |
          dotnet new classlib -f net6.0 -n net6test -o ./examples/netcore6
          dotnet add ./examples/netcore6/net6test.csproj package HotPotato.Core --version '${{ inputs.version }}' -s "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --no-restore
          dotnet restore ./examples/netcore6/net6test.csproj
          dotnet build ./examples/netcore6/net6test.csproj --no-restore
