name: "Run .NET Framework Tests"
# Since these have to run on a separate Windows node, I thought it would be efficient to have them run only on PRs

on:
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: windows-2019

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Build
      run: |
        dotnet build --configuration NETFRAMEWORK
    - name: Run .NET Framework Tests
      run: |
        dotnet test ./test/HotPotato.NetFramework.Test/HotPotato.NetFramework.Test.csproj -c Release
