---
name: Release Hot Potato

on:
  push:
    branches:
      - '*'
  # release:
  #   types:
  #     - "released"

jobs:
  push-package:
    runs-on: ubuntu-latest
    steps:
      - name: Pull artifacts from release
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release download ${{ github.event.release.tag_name }} --dir ./artifacts

      - name: Setup .NET 6.0
        uses: actions/setup-dotnet@v3.2.0
        with:
          dotnet-version: 6.0.x

      - name: Publish nuget packages
        run: dotnet nuget push ./artifacts/**/*.nupkg -k '${{ secrets.NUGET_PUSH }}' -s https://api.nuget.org/v3/index.json --skip-duplicate
